DROP TABLE IF EXISTS CUSTOMER;
DROP TABLE IF EXISTS ACCOUNT;
DROP TABLE IF EXISTS TRANSFER_HISOTRY;

CREATE TABLE CUSTOMER(
    ID LONG AUTO_INCREMENT PRIMARY KEY NOT NULL,
    FULL_NAME VARCHAR(50)
);

CREATE TABLE ACCOUNT(
    ID LONG AUTO_INCREMENT PRIMARY KEY NOT NULL, 
    CUSTOMER_ID LONG,
    BALANCE DECIMAL(20,2)
);

CREATE TABLE TRANSFER_HISOTRY(
    ID LONG AUTO_INCREMENT PRIMARY KEY NOT NULL, 
    SENDER_ID LONG,
    RECIPIENT_ID LONG,
    AMOUNT DECIMAL(20,2),
    TIMESTAMP_SECOND LONG
);

ALTER TABLE ACCOUNT ADD FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMER(ID);

ALTER TABLE TRANSFER_HISOTRY ADD FOREIGN KEY(SENDER_ID) REFERENCES ACCOUNT(ID);
ALTER TABLE TRANSFER_HISOTRY ADD FOREIGN KEY(RECIPIENT_ID) REFERENCES ACCOUNT(ID);


ALTER TABLE ACCOUNT ALTER COLUMN ID RESTART WITH 10001;